### ISSUE TITLE
chinese prompt template needed

### ISSUE THREAD

**Issue by zhpmatrix** [wyl-willing/MindMap#4]
can you share the chinese prompt template?

for example:

<img width="1302" alt="截屏2024-02-22 上午10 43 02" src="https://github.com/wyl-willing/MindMap/assets/4077026/d396140c-7094-420d-98c0-9ec5e78f6773">

**Comment by wyl-willing** [comment]
Sure, you can see Chinese template in
MindMap/pre-training/cmcqa/MindMap_CMCQA.py
at main · wyl-willing/MindMap (github.com)
<https://github.com/wyl-willing/MindMap/blob/main/pre-training/cmcqa/MindMap_CMCQA.py>
.

If you still have any questions, please let me know.

Yilin

张大千 ***@***.***> 于2024年2月22日周四 10:44写道：
